"""add chunk embeddings

Revision ID: 4ebbb85f68d5
Revises: 5efc87dac25a
Create Date: 2026-08-12 03:05:40.372677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ebbb85f68d5'
down_revision: Union[str, Sequence[str], None] = '5efc87dac25a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_chunks', sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_chunks', 'embedding')
    # ### end Alembic commands ###
